image: node:20

stages:
  - build
  - test

# Instalar dependencias del backend
build_backend:
  stage: build
  script:
    - cd backend
    - npm install

# Ejecutar pruebas (Esto fallará hasta que configures un test real)
test_backend:
  stage: test
  script:
    - cd backend
    - npm install
    - npm test
